### PR TITLE
fix(Ingestion): Elastic http/https host support

### PR DESCRIPTION
**Pull request by abiwill**
allow users to specify url scheme. enable ingestion from both TLS enabled clusters.
currently specifying the url scheme resulted in assertion error.

## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by shirshanka** [comment]
Thanks for this @abiwill 
I fixed up the regex to handle the old style as well.. 
could you add a unit test here? 
https://github.com/linkedin/datahub/blob/master/metadata-ingestion/tests/unit/test_elasticsearch_source.py

That will ensure we handle different styles of host_port specification correctly.

**Comment by abiwill** [comment]
Unittest PR: https://github.com/linkedin/datahub/pull/4194
Thanks for the fix @shirshanka 
There is one more problem with the regex: \w allows use of _ which is not a valid hostname.
Let me know if you would like to change the regex to: ^[(http|https)://]*[0-9a-zA-Z\-\.\:]+[\/]*$

**Comment by mmmeeedddsss** [comment]
It is impressive that only changing the validation regex solves the issue. It is fascinating to see a project growing in such a way. 

I want to thank you for spending your time on investigating, implementing and testing this change. 🚀

**Comment by abiwill** [comment]
I have just started my journey into programming. Trying to learn and solve :)

**Comment by shirshanka** [comment]
Since this check is really a first line of defense, I think it is okay to be a bit more loose, since the underlying elastic client will anyway complain if it cannot connect to the configured endpoint.

**Review by shirshanka — APPROVED** [review]
LGTM! Made changes to unit test in this PR itself.

**Pull request merged**
