### PR TITLE
fix(react): fix graphql apollo cache update issue cause of usagestats

### PR DESCRIPTION
**Pull request by topwebtek7**
## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Review by gabe-lyons — APPROVED** [review]
Thanks for catching this-- I think a better solution would be to add usageStats to the updateDataset query

**Comment by topwebtek7** [comment]
> Thanks for catching this-- I think a better solution would be to add usageStats to the updateDataset query

but `usageStats(resource: $urn, range: MONTH) {` needs urn parameter but updateDataset doesn't have that.. (instead has input)
usageStats would work without urn?

**Review by gabe-lyons — APPROVED** [review]
I see what you're saying- ok let's merge this as is to fix & followup later with a more sustainable solution

**Review by shirshanka — APPROVED** [review]
LGTM!

**Pull request merged**
