### PR TITLE
docs(website): Move company logos into tabs categorized by industry

### PR DESCRIPTION
**Pull request by jeffmerrick**
Screen Shot 2022-02-17 at 4 13 24 PM

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by jjoyce0510** [comment]
One minor comment - What's the diff between E-Commerce and B2C? These categories don't seem mutually exclusive.. Is that intentional?

**Comment by maggiehays** [comment]
\

> One minor comment - What's the diff between E-Commerce and B2C? These categories don't seem mutually exclusive.. Is that intentional?

**Comment by jjoyce0510** [comment]
I'd prefer just E-commerce. It's more standard. Still doesn't seem quite right.. Since Peloton could be considered ecommerce. Maybe not time to slice these upp..

**Review by shirshanka — APPROVED** [review]
LGTM!

**Pull request merged**
