### PR TITLE
feat(react): add dataJob, dataFlow entities and preview, profile pages and graphql mock & refactor with fragments

### PR DESCRIPTION
**Pull request by topwebtek7**
## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Review by gabe-lyons — APPROVED** [review]
looks good to me!

**Review by shirshanka — APPROVED** [review]
LGTM! Much cleaner with fragments :)

**Review by jjoyce0510 — COMMENTED** [review]
Awesome work!

**Review by shirshanka — APPROVED** [review]
LGTM! Thanks @topwebtek7

**Pull request merged**
