### PR TITLE
fix(ingest): remove datahub.metadata import shortcut

### PR DESCRIPTION
**Pull request by hsheth2**
We don't need three distinct ways to import the model classes. This is the first step of simplification.

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by shirshanka** [comment]
Is this change backwards compatible?

**Comment by hsheth2** [comment]
This is not backwards compatible. My understanding is that we were using this in a very small number of places, and migrating is as simple as changing `from datahub.metadata import X` with `from datahub.metadata.schema_classes import X`.

**Comment by shirshanka** [comment]
@adriaanslechten @frsann @joemirizio: thoughts on this change? will it break you?

**Comment by adriaanslechten** [comment]
Should be an easy fix if so. And simplification is always a good thing. 😄

**Comment by joemirizio** [comment]
I was also using the `datahub.metadata.com.linkedin.pegasus2avro.*` path, but I can switch to `schema_classes`. 

The namespace at the end of the path in the old version did feel slightly more natural (e.g. `schema` in `from datahub.metadata.com.linkedin.pegasus2avro.schema import SchemaField`), but I'd also prefer there to be just one way to do it.

**Comment by frsann** [comment]
All good on out end!

**Review by shirshanka — APPROVED** [review]
LGTM! 
@hsheth2 : since this is technically backwards incompatible, please bump the major version when you publish to PyPi

**Pull request merged**
