### PR TITLE
feat(react): moving filter panel from modal to drawer

### PR DESCRIPTION
**Pull request by topwebtek7**
## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by shirshanka** [comment]
@topwebtek7 : looks like you have some extra commits that got merged in ... could you clean up the commits to only include your changes?

**Comment by topwebtek7** [comment]
> @topwebtek7 : looks like you have some extra commits that got merged in ... could you clean up the commits to only include your changes?

Sure

**Comment by shirshanka** [comment]
Thanks! 
Could you also drop in a screenshot for how this looks after your change?

**Comment by topwebtek7** [comment]
image

**Review by shirshanka — APPROVED** [review]
LGTM!
Thanks @topwebtek7 :)

**Pull request merged**
