### PR TITLE
rfc(RBAC): Fine-Grained Access Controls in GMS

### PR DESCRIPTION
**Pull request by jjoyce0510**
[Rendered](https://github.com/linkedin/datahub/blob/80b4d23a66025adecd6f449f82a042682546cc01/docs/rfc/active/rbac/rbac.md). 

This PR includes an RFC for adding fine-grained access control to DataHub GMS. Specifically, we propose introduction of the following concepts

- actor
- resource
- policy
- role
- role mapping

into GMS along with the development of various new components:

- authentication filter
- authenticator
- role resolver
- authorizer

all in order to unlock the ability to a) declare granular access control policies against resources stored within the DataHub platform and b) associate them with actors in your company's ecosystem (ie. users and groups from an internal IdP).

We aim to build something that is suitable for a wide range of companies & able to change gracefully as requirements evolve. 

Please take a look and feel free to jump into the discussion. Hoping for lots of community participation on this one. :)

### CODE REVIEW

**Comment by jjoyce0510** [comment]
Topic of discussion: How to support automatically creating read / write roles for _owners_ of a particular data assets? 

Options I can imagine:

1. MAE Consumer that automatically writes new Roles & Policies when a Data asset's ownership changes. 
2. Concept of "virtual" roles that are generated within the Authenticator component. Pluggable filters permit enrichment and resolution of policies that are not necessarily persisted in the DB. This avoids have to persist roles for _every single data asset_ in storage.

Any other suggestions?

Once we come to an answer here, I'll update the RFC to reflect!

**Review by zirx — CHANGES_REQUESTED** [review]
In general it would be nice to have it aligned with the existing domain model in DataHub.
RBAC should be defined not only for entities, but also for relationships - for example define roles for using relations `Consumes`, `ReportsTo`, `Produces`, `DownstreamOf`, `Contains` 

There is no need in specific `Actor` when CorpUser and CorpGroup can represent actors from RFC, and OwnedBy can represent ownership (who can create/modify entity or relationship), ReportsTo and Consumers can define who can read entity. 

There are several cases which are not covered in this RFC, but can be really useful for large companies (based on my experience in finance industry):
1. Multitenancy, which can be useful for SaaS providers - how to isolate visibility and administration of entities/relations for specific `namespace` (external consumer for the SaaS provider)
2. Delegate administration to metadata owners by using CorpUser and CorpGroup, resolved by OwnedBy relationship. It can be better aligned with push integration over Kafka (producers can specify ACL for consumers). This can be a good feature for usage in large companies, where read access to metadata is usually not restricted, but metadata management controlled by metadata owners in each department.
3. Restrict access to upstream/downstream relationships in lineage graph. For example, if some entity cannot be referenced or reused without explicit approval from metadata owner. It can be useful if such metadata is deprecated, so access to it should be restricted (again, it's about access rights for relationships, not for entity).

Limiting access rights to CRUD can be enough for isolated entities, but allow/disallow access to relationships seems more attractive for real-world use-cases.
Another idea is about using visibility for entities which now defined with `AccessLevel`: `PUBLIC`/`PRIVATE`. For example user can see some public fields, but only `Owner` or `Consumer` has access to private fields.

I also recommend to revisit `RBAC` and `ACL` specifications in Kafka https://docs.confluent.io/platform/current/kafka/authorization.html#acl-concepts https://docs.confluent.io/platform/current/security/rbac/index.html# which could provide good insights about setting RBAC for ETL topics (similar to lineage in DataHub)

**Comment by jjoyce0510** [comment]
Hi @zirx!

First of all, thank you for the feedback! Initially, we had thought that because access patterns for the data related to RBAC would differ quite a bit from more typical metadata graph entities, we had decided to conceptually split the data model into 2 pieces: 1) the "metadata graph" (entities, aspects, and the relationships between them) and 2) the DataHub "control plane" data, ie the system data required to operate a DataHub deployment.

I'm going to spend some time challenging these assumptions, & thinking through a solution wherein we model everything on the metadata graph. From a level of effort perspective, this type of solution is preferred because it should be less painful to back out of in the case that we do need more deliberate separation of the data planes. 

Let me respond in some time with a more thoughtful consideration of modeling roles, policies, & mappings as part of the core metadata graph. In the meantime, I'll continue to review the resources you've provided and other reference implementations of these concepts.

Thanks again
John

**Comment by zirx** [comment]
@jjoyce0510 sorry for a delayed response, the 3rd item was about `default` access to some paths in lineage, for example restrict consumption from upstream source by default, allow it only for some dedicated components which added as exclusion. In the same way some upstream sources can be open by default for everyone (open govt api as example), can be restricted explicitly. 
Why it's important? For example, some personal medical info should be treated as confidential, so access to it should be restricted by default - any derived usage should be prohibited as well. On the contrary, open sources like census data are open for usage and sharing (deriving) by everyone.

**Comment by dingobar** [comment]
For us, it is not important who can see what (at least not yet), but rather that the entity (person or group) that created a resource in GMS is the only one besides admins that can change it.

**Comment by sgomezvillamor** [comment]
This looks really great!

With access control policies based on a combination of resource type and/or resource identifier, the pattern matching on the resource identifier is really nice. For example, it allows for restricting the policy to all datasets in a given platform. _Eg_ `urn:li:dataset:(urn:li:dataPlatform:platformX,*,*)`. However, this is limited to the URN hierarchy. 

What about extending this ability with resources having some specific value for some property in some aspect? _Eg_ datasets having a given tag, or datasets being produced by some team, etc.

**Comment by jjoyce0510** [comment]
Thanks for all the great feedback and discussion! Still digesting some of it, but one thing I've heard loud and clear from folks in the community is that Ownership-Based controls are absolutely critical. 

As described at the bottom of the doc, we plan to support this using a specific "Ownership" Authorizer, which will resolve the Ownership information associated with an entity if applicable and check whether the Actor is indeed considered an owner. There will not be a requirement to define any policies to enable this behavior. Instead, we'll provide a global configuration to enable / disable this behavior in aggregate.

In addition to this, we will support fine grained access policies using a separate API. These will be enforced using a different "Policy" Authorizer, which will run alongside the Ownership Authorizer in the same chain. 

@amarathavale : Firstly, thank you for taking the time to read this and provide feedback! 

So what we have here is really no longer "true RBAC", and in fact is now more akin to "ABAC". I agree in general with the benefits of traditional RBAC you pointed out: namely, the ability to reuse the same role across a different policies. However, after some consideration, we've decided to roll out something simpler than RBAC, wherein a "Policy" directly specifies a group of relevant actors it applies to (Users / Groups) along with a list of [action, resource spec] pairs defining which actions the actors can perform against specific resources. This is effectively a "mega policy" model in which everything about who can do what is into larger document structures. 

The pros of this are 
- simplicity in modeling: There are less abstractions / layers of indirection operators of DataHub have to understand. Instead, they just work with a list of "Policies" 
- evolvability: if we decide that roles are necessary, we should be able to add them relatively easily in the future (since we are only making things more complex) 

while trading off 
- the flexibility that comes with the intermediary abstraction of a "role"
- the ability to easily understand which privileges are associated a particular individual (single Many policies point to actors, as opposed to actors pointing to policies) 

What I'm saying is: In the first pass, there will be no notion of "role". There will only be named "policies" that privileged users of DataHub can view and modify. A single policy document can contain the following:
- Actor Filters: Specific users and groups who the policy applies to
- A list of 
     - Action: VIEW, VIEW_AND_MODIFY
     - Resource Filter: Which resource the action is permitted against. 
at authorization time, the Policy-based authorizer component will have loaded the set of all policies, and will execute which policies applied give the current actor, action, and resource. Does this make sense? 

Agree in general that mapping rules make understanding who has access to what more difficult, so in the first version we will only support selecting concrete users and groups in the policy definition. Users who have not been seen before will be associated with a blanket "default" policy, which can be changed by the operator. The assumed benefit of flexible mapping rules is that operators don't need to make changes to role mappings each time a new user or group is onboarded from a third party IdP. I don't have enough signal at this time to make a judgement call about how important this really is to the system, hence we are omitting in V1.

**Comment by amarathavale** [comment]
@jjoyce0510 : The {Actor + Action + Resource specification} model for a Policy definition makes sense, and solves the problem at hand. There's no one-way to implement this. If someone decides to split it into Roles, Actors.... it'd be better to model it using the 3-part approach for familiarity (e.g. [AWS](https://aws.amazon.com/blogs/database/introducing-role-based-access-control-for-amazon-documentdb-with-mongodb-compatibility/), [Azure](https://docs.microsoft.com/en-us/azure/active-directory/roles/custom-overview)).

Appreciate the detailed response/explainer.

**Comment by jjoyce0510** [comment]
Update: We are working on building out the first instantiation of this right now.

**Review by shirshanka — APPROVED** [review]
Update: Policies V1 has been released. See the [Policies Guide](https://datahubproject.io/docs/policies/) on how to use it. Glad to see all the progress here! 

Going to commit these docs for historical reference.

**Pull request merged**
