### PR TITLE
Adding openapi ingestion

### PR DESCRIPTION
**Pull request by vlavorini**
## Checklist
- [X] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by jjoyce0510** [comment]
I see we are modeling OpenAPI resources as "Datasets". Does this make sense, or should we introduce an API / Service concept here?

**Comment by vlavorini** [comment]
Maybe it worth to describe one use-case.
All the Apple branded devices belonging to our institution are managed from  [JAMF](https://www.jamf.com).
If the analytics team needs to check how many X applications are actually installed on the devices, they need to gather the relative dataset from their [APIs](https://www.jamf.com/developers/apis/classic/overview/), because JAMF is deployed on the cloud and we cannot access directly to the internal DB.
So it's good for us to have those APIs defined in our catalog.

**Comment by shirshanka** [comment]
Thanks for the contribution @vlavorini ! Let's get this in after adding API-s to the metadata model.

**Comment by vlavorini** [comment]
Hi @shirshanka , just added an integration test. Thank you!

**Review by shirshanka — APPROVED** [review]
LGTM! Thanks for your patience with this @vlavorini

**Pull request merged**
