### PR TITLE
feat(ingest): add underlying platform for glue

### PR DESCRIPTION
**Pull request by aseembansal-gogo**
This is in place of earlier PR https://github.com/linkedin/datahub/pull/2985. 

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by aseembansal-gogo** [comment]
I think the other changes might be because in this https://github.com/linkedin/datahub/pull/3030 the commands were not run.

Are the tests on github different compared to what is mentioned in https://datahubproject.io/docs/metadata-ingestion/developing#testing @shirshanka ?

**Comment by shirshanka** [comment]
Hi @aseembansal-gogo 

Platforms are special entities, they indicate technologies which have logos, and can have UI behavior attached to them. I don't think we want to allow unfettered ability to replace platform names with other strings. 

In fact we have allowed this in some other sources (like looker) and want to remove this capability. 

We will introduce the concept of "instances" which will allow you to express free-form labels like "data-warehouse" to attach to these systems. 

I would like to propose a modification to your current approach where: 
1. In the special case where glue is attached to an athena-only warehouse, one can replace the platform `glue` with the underlying_platform `athena`  (hence staying away from the verbiage platform_alias)
2. This list of replacements allowed should be a controlled list of platforms, which will start with just 1 option for now: `athena`

Hope this will unblock you.

**Review by shirshanka — APPROVED** [review]
LGTM! Thanks for making the changes.

**Review by shirshanka — APPROVED** [review]
LGTM

**Pull request merged**
