### PR TITLE
fix(dataset): Use platform delimiter to compose the browse paths

### LINKED ISSUE #1956: Use PlatformInfo to better compose browse paths
**Is your feature request related to a problem? Please describe.**
Dataset names that have `.` in them are split by the browse endpoint regardless of the [Platform delimiter](https://github.com/linkedin/datahub/blob/f0485a490e08445d1459de3cd697c6cc0b2189d5/metadata-models/src/main/pegasus/com/linkedin/dataplatform/DataPlatformInfo.pdl#L72). See the bread crumbs in the image below:

image

I didn't expect to see the last two crumbs to be `a` and `test`. Instead I expected to see one unified crumb `a.test`. 

**Describe the solution you'd like**
It seems like we always split on `.` [here](https://github.com/linkedin/datahub/blob/master/metadata-builders/src/main/java/com/linkedin/metadata/builders/search/DatasetIndexBuilder.java#L32) but perhaps we can use the the [Platform delimiter](https://github.com/linkedin/datahub/blob/f0485a490e08445d1459de3cd697c6cc0b2189d5/metadata-models/src/main/pegasus/com/linkedin/dataplatform/DataPlatformInfo.pdl#L72) to be smarter about this?

The desired end result would be to treat `.` in dataset names as any other alphanumeric character for platforms that use a different delimiter.

**Describe alternatives you've considered**
No alternatives have been considered

**Additional context**
Using `.` in names is not very uncommon. Supporting them properly would facilitate DataHub adoption.

### PR DESCRIPTION
**Pull request by nagarjunakanamarlapudi**
fix(dataset): Use platform delimiter to compose the browse paths. Fixes #1956

- DataPlatforms API will now extend GMS' BaseEntityResource
- Dataset Index Builders are injected with Rest.li client to hit dataPlatforms API for delimiter

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Review by hshahoss — APPROVED** [review]
lgtm

**Comment by jplaisted** [comment]
1) Is this a breaking change? Can you document that? https://github.com/linkedin/datahub/blob/125ae288f1601bef2c42f44db6d8eb58b380a304/docs/CONTRIBUTING.md#footer
2) Should this maybe be at least two PRs? One to update the server, and another to update the index builder?

**Comment by nagarjunakanamarlapudi** [comment]
> 2. Should this maybe be at least two PRs? One to update the server, and another to update the index builder?

I could do that as well. Any harm in doing this in a single PR ?

**Comment by jplaisted** [comment]
The general harms of doing things in multiple PRs:

- Harder to review
- Harder to roll back
- More risk

**Comment by nagarjunakanamarlapudi** [comment]
> The general harms of doing things in multiple PRs:
> 
> * Harder to review
> * Harder to roll back
> * More risk

Agreed. created #2057 to update the server

**Comment by nagarjunakanamarlapudi** [comment]
Looks like an issue with rebase. Will create a new PR

**Pull request closed without merging**
