### PR TITLE
feat: add description field to dataset index mapping

### PR DESCRIPTION
**Pull request by camelliazhang**
## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by camelliazhang** [comment]
> Assuming you've tested this end-to-end

yep, existing data is cleaned & index rebuilt. 
- Clean up the existing es mapping data
- docker-compose build elasticsearch-setup
docker-compose pull && docker-compose up elasticsearch-setup

**Comment by mars-lan** [comment]
I assume you'll have a follow-up PR that updates the builder logic? We should also add a document on how to migrate search index mapping.

**Comment by camelliazhang** [comment]
> I assume you'll have a follow-up PR that updates the builder logic? We should also add a document on how to migrate search index mapping.

Sorry I should have provided more context on this PR:
1. The description field is already defined in dataset document model
2. The logic in index building exists too:
`  private DatasetDocument getDocumentToUpdateFromAspect(@Nonnull DatasetUrn urn, @Nonnull DatasetProperties datasetProperties) {
    final DatasetDocument doc = setUrnDerivedFields(urn);
    if (datasetProperties.hasDescription()) {
      doc.setDescription(datasetProperties.getDescription());
    }
    return doc;
  }`
The only missing piece is the description field in index mapping. The old behavior (before this PR) is: even if this field is not defined in the index mapping, we can still ingest the data into search index because ES goes schema-less & automatically added this field into index mapping. This inconsistency info confused the user. The root cause is the index builder provides an implicit mapping between aspects & search document fields, no validation against ES schema (good or bad).

**Comment by camelliazhang** [comment]
> > I assume you'll have a follow-up PR that updates the builder logic? We should also add a document on how to migrate search index mapping.
> 
> Sorry I should have provided more context on this PR:
> 
> 1. The description field is already defined in dataset document model
> 2. The logic in index building exists too:
>    `  private DatasetDocument getDocumentToUpdateFromAspect(@Nonnull DatasetUrn urn, @Nonnull DatasetProperties datasetProperties) { final DatasetDocument doc = setUrnDerivedFields(urn); if (datasetProperties.hasDescription()) { doc.setDescription(datasetProperties.getDescription()); } return doc;   }`
>    The only missing piece is the description field in index mapping. The old behavior (before this PR) is: even if this field is not defined in the index mapping, we can still ingest the data into search index because ES goes schema-less & automatically added this field into index mapping. This inconsistency info confused the user. The root cause is the index builder provides an implicit mapping between aspects & search document fields, no validation against ES schema (good or bad).

As for the documentation, yes, there will be a follow up.

**Comment by mars-lan** [comment]
Got it. Is there an opening issue on this we can close now?

**Comment by camelliazhang** [comment]
@mars-lan I think we can close https://github.com/linkedin/datahub/issues/1736

**Pull request merged**
