### PR TITLE
feat(ingestion): Support for converting AVRO schemas with logical types to MCE fields.

### PR DESCRIPTION
**Pull request by rslanka**
Adds support for converting AVRO schemas with logical types to MCE fields.
## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Review by shirshanka — APPROVED** [review]
LGTM!

**Comment by shirshanka** [comment]
Will wait for CI to be green before merging.

**Review by shirshanka — APPROVED** [review]
LGTM!

**Comment by serefacet** [comment]
This PR fixes my existing issue! Thank you @rslanka :) You saved my day

**Pull request merged**
