### PR TITLE
Add AWS MSK Iam Auth Jar to GMS 

### PR DESCRIPTION
**Pull request by arunvasudevan**
## Checklist
- [ X] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))

In order to use the MSK with IAM and with SASL Mechanism as `AWS_MSK_IAM` and security protocol as `SASL_SSL` AWS MSK IAM Jar should be added to the Project Dependencies.

Here are the env variables that's used in the GMS Project

```
SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
SPRING_KAFKA_PROPERTIES_SSL_TRUSTSTORE_LOCATION=/tmp/kafka.client.truststore.jks
SPRING_KAFKA_PROPERTIES_SASL_MECHANISM=AWS_MSK_IAM
SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG=software.amazon.msk.auth.iam.IAMLoginModule required awsDebugCreds=true;
SPRING_KAFKA_PROPERTIES_SASL_CLIENT_CALLBACK_HANDLER_CLASS=software.amazon.msk.auth.iam.IAMClientCallbackHandler
```

AWS MSK IAM Auth Project - https://github.com/aws/aws-msk-iam-auth
Related Issue on AWS MSK IAM Project  - https://github.com/aws/aws-msk-iam-auth/issues/50

### CODE REVIEW

**Comment by shirshanka** [comment]
@arunvasudevan : a build failure snuck in between your PR and main branch. Can you rebase?

**Comment by arunvasudevan** [comment]
@shirshanka Rebased and pushed it, may be 3rd time is the charm.

**Comment by arunvasudevan** [comment]
Build failures doesn't seem to be related to the changes.

**Review by dexter-mh-lee — COMMENTED** [review]
Should we add the implementation higher up the chain? Putting it in war means, it will not be included in standalone mae/mce consumers

**Comment by arunvasudevan** [comment]
@dexter-mh-lee Its mainly needed for 4 modules IMO - `metadata-service`, `datahub-frontend`, `mce` and `mae`
As these are the services that connects to Kafka/MSK.

Even in the overall project gradle file we might have to apply this dependency by selecting each of the project names as there are no common plugins between these modules. (Metadata service gradle file doesn't have dependency on kafka. Also kafka is a dependency and not a plugin)
So, We can add the dependency in other projects individually rather than an `afterEvaluate` condition on the main one.

**Comment by arunvasudevan** [comment]
@shirshanka Looks like 5th time is the charm. 👍🏻

**Comment by dexter-mh-lee** [comment]
Sounds good. Then can we add to gms/mae/mce consumers in this PR

**Review by dexter-mh-lee — APPROVED** [review]
LGTM! cc @shirshanka

**Comment by arunvasudevan** [comment]
Looks like after this fix - https://github.com/linkedin/datahub/commit/2dab22e17fdc03763a2a97a2cbec5f8bd6c68db7 builds are succeeding consistently.

**Review by shirshanka — APPROVED** [review]
LGTM

**Pull request merged**
