### PR TITLE
feat(mlFeatureTable): add graphql, ui/ux for mlFeatureTable, mlFeature, mlPrimaryKey entities

### PR DESCRIPTION
**Pull request by topwebtek7**
## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

Screen Shot 2021-07-16 at 12 13 54 AM
Screen Shot 2021-07-16 at 2 33 49 AM
Screen Shot 2021-07-16 at 2 36 00 AM

### CODE REVIEW

**Comment by shirshanka** [comment]
Is there any demo data with this PR?

**Comment by topwebtek7** [comment]
> Is there any demo data with this PR?
there was a ingestion Kevin added and no demo data in this PR

**Comment by topwebtek7** [comment]
fixed conflicts

**Review by shirshanka — APPROVED** [review]
LGTM!

**Pull request merged**
