### PR TITLE
fix(docker): Run as non-root user in docker

### PR DESCRIPTION
**Pull request by frsann**
This PR fixes the issue of the services being run as root, which is suboptimal as the code executed in the container can get root access on the host machine. We add a `datahub` user and group in the Docker images, and the services are run using that user.  

## Checklist
- [X] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by frsann** [comment]
The frontend creates a pid file, and the user needs write access to do it. Let me know if you think this should be handled in some other way. 

Did a quick smoke test and it seems to work, but let me know if some further testing is needed. 🙏

**Comment by mars-lan** [comment]
Thanks for the contribution! This LGTM on a glance. Will have @keremsahin1 & @jplaisted give the final approval.

**Comment by jacopoch** [comment]
LGTM ✨

**Comment by jplaisted** [comment]
LGTM, assuming images still start and logs are readable.

**Comment by frsann** [comment]
Yes, they start and logs from all services show up.

**Pull request merged**
