### PR TITLE
Update metadata-models 94.0.0 -> 100.0.1

### PR DESCRIPTION
**Pull request by jplaisted**
## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by jplaisted** [comment]
Hey @jywadhwani @keremsahin1 the tests are failing here and I'm not sure why. I think you've edited these recently? Can you please take a look?


```
> Task :metadata-restli-resource:test

Gradle suite > Gradle test > com.linkedin.metadata.restli.BaseEntityResourceTest.testFilterFromIndexEmptyAspects FAILED
    java.lang.AssertionError at BaseEntityResourceTest.java:489

Gradle suite > Gradle test > com.linkedin.metadata.restli.BaseEntityResourceTest.testFilterFromIndexWithAspects FAILED
    java.lang.AssertionError at BaseEntityResourceTest.java:522

> Task :gms:impl:test FAILED

Gradle suite > Gradle test > com.linkedin.metadata.resources.dataplatform.utils.DataPlatformsUtilTest.testGet FAILED
    java.lang.NoSuchFieldError at DataPlatformsUtilTest.java:15

Gradle suite > Gradle test > com.linkedin.metadata.resources.dataplatform.utils.DataPlatformsUtilTest.testGetPlatformDelimiter FAILED
    java.lang.NoClassDefFoundError at DataPlatformsUtilTest.java:63

Gradle suite > Gradle test > com.linkedin.metadata.resources.dataplatform.utils.DataPlatformsUtilTest.testGetPlatformType FAILED
    java.lang.NoClassDefFoundError at DataPlatformsUtilTest.java:44

Gradle suite > Gradle test > com.linkedin.metadata.resources.dataplatform.utils.DataPlatformsUtilTest.testIsValidPlatform FAILED
    java.lang.NoClassDefFoundError at DataPlatformsUtilTest.java:53

9 tests completed, 4 failed

> Task :metadata-restli-resource:test FAILED

67 tests completed, 2 failed

> Task :metadata-dao-impl:ebean-dao:test

Gradle suite > Gradle test > com.linkedin.metadata.dao.EbeanLocalDAOTest.testGetAspectsWithIndexFilter FAILED
    java.lang.AssertionError at EbeanLocalDAOTest.java:818

48 tests completed, 1 failed

> Task :metadata-dao-impl:ebean-dao:test FAILED

```

**Comment by jplaisted** [comment]
FYI that last commit is a cherry pick to fix the build. It is from an internal change, but I skipped over a few others to get it.

**Review by jywadhwani — APPROVED** [review]
Assuming end-to-end testing is done

**Comment by jplaisted** [comment]
Ah, yes, let me run through an e2e test, thanks :)

**Comment by jplaisted** [comment]
Done. 

- Cleared my docker volumes.
- Built with gradle.
- Started datahub with docker/dev.sh.
- Logged in.
- Verified no existing metadata in datahub.
- Ran docker/ingestion/ingestion.sh.
- Verified I now see datasets under "datasets I own".
- Verified I can search for datasets.
- Verified I can see schemas.
- Verified I can see lineage.

**Pull request merged**
