### PR TITLE
feat(react): configure Cypress + MirageJS + GraphQL mock for functional testing plus a couple of example tests

### PR DESCRIPTION
**Pull request by wan54**
## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by wan54** [comment]
To test this out:

1. Checkout this branch
2. `yarn install`
3. `yarn test:e2e:ci`

**Comment by gabe-lyons** [comment]
Thanks @wan54 - this looks great

**Comment by wan54** [comment]
Have just rebased and fixed the lint error

**Comment by shirshanka** [comment]
@wan54 : we will get to this PR in the next week. Thanks for being patient!

**Review by shirshanka — APPROVED** [review]
LGTM! Thanks @wan54, @topwebtek7 @gabe-lyons for the collab.

**Pull request merged**
