### PR TITLE
ci: update rename-namespace.sh to specify /bin/bash 

### PR DESCRIPTION
**Pull request by stephenp-gr**
ci: update rename-namespace.sh to specify /bin/bash 

On some variants of linux /bin/sh isn't necessarily bash, this is to allow builds to succeed on these platforms.

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by treff7es** [comment]
Your change would work with `bash` but I think if the script is not bash specific then it is better to use /bin/sh as it is more generic.

**Comment by shirshanka** [comment]
@stephenp-gr : what is the behavior of this script when the shell is not `bash`? Does it fail?

**Comment by stephenp-gr** [comment]
You are totally correct that this would limit usage to exclusively bash, as the script uses BASH_SOURCE[0].
After a little research, I've found there is a better shell agnostic way forward.

**Review by shirshanka — APPROVED** [review]
LGTM!

**Pull request merged**
