### PR TITLE
feat(ingest): add transformer to add properties

### PR DESCRIPTION
**Pull request by nomarlo**
Propose to use a class instead of just a function to have a more explicit contract

## Checklist
- [X] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [X] Tests for the changes have been added/updated (if applicable)
- [X] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by shirshanka** [comment]
Thanks for the PR @nomarlo and sorry for kicking off CI so late
Seems like `lint` is failing.. seems like a simple check needed to make sure that variable is not None before using it.

**Comment by nomarlo** [comment]
Hey @shirshanka it should be fixed

**Comment by nomarlo** [comment]
Hey, @shirshanka in the last GitHub Actions I saw some errors in the tests related to Kafka, that seemed unrelated to my work. Either way, I rebased from master. I include some screenshots from linters, formatter, tests, etc running fine in my local 

Screen Shot 2021-11-08 at 3 14 49 PM

Screen Shot 2021-11-08 at 3 16 52 PM

Let me know if I'm missing something here. Thanks

**Comment by shirshanka** [comment]
@nomarlo : will get this in today 🙏

**Review by shirshanka — APPROVED** [review]
LGTM!

**Pull request merged**
