### PR TITLE
chore: renaming business_glossary rfc directory with pull request number

### PR DESCRIPTION
**Pull request by shirshanka**
## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Review by jjoyce0510 — APPROVED** [review]
i guess no links to this one? if so, lgtm

**Comment by jjoyce0510** [comment]
Hey one thing -- do we need to update references inside of datahub-docs-website/sidebars.js to point to the new docs? See: https://github.com/linkedin/datahub/blob/master/docs-website/sidebars.js#L115

**Comment by shirshanka** [comment]
Yeah I had fixed that in the second commit.

**Review by woodyzhou — APPROVED** [review]
LGTM

**Pull request merged**
