### PR TITLE
DataTasks

### PR DESCRIPTION
**Pull request by portintegration**
## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by jplaisted** [comment]
Hey can you please add more details to this PR? "DataTasks" isn't very descriptive. Please detail what this is and why you're adding it. Thanks!

**Comment by jjoyce0510** [comment]
@portintegration Hi there! Thanks for the PR. Will you be continuing to update this?

**Comment by jjoyce0510** [comment]
@shirshanka Can we close this due to inactivity? 

cc. @portintegration 

We now have mainlined helm charts which should be able to aid you in your deployment to GKE. cc. @dexter-mh-lee who has worked on this.

**Comment by shirshanka** [comment]
Closing this due to inactivity and presence of helm charts.

**Pull request closed without merging**
