### PR TITLE
fix(graphql): add ElasticSearch path prefix configuration

### PR DESCRIPTION
**Pull request by zhoxie-cisco**
## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by zhoxie-cisco** [comment]
Some ElasticSearch API with proxy need to configure the path prefix
e.g. https://eshost/path/

**Review by dexter-mh-lee — APPROVED** [review]
LGTM!

**Review by shirshanka — APPROVED** [review]
LGTM!

**Pull request merged**
