### PR TITLE
feat(datahub-dao): enable services to access gms over https

### PR DESCRIPTION
**Pull request by thomasplarsson**
Fixes https://github.com/linkedin/datahub/issues/2113

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by shirshanka** [comment]
Thanks for the contribution @thomasplarsson!
Could you also update the docs to indicate how to configure ssl for the frontend and the rest.li server? 
Presumably the README-s at: https://github.com/linkedin/datahub/tree/master/datahub-frontend and https://github.com/linkedin/datahub/tree/master/gms ?

**Comment by thomasplarsson** [comment]
Hi @shirshanka. 
We have not actually configured the servers (rest.li or frontend) themselves to use SSL but relied on having EC2 load balancers in front terminating the SSL connection. So I don't have any knowledge at the moment on how that would be accomplished. Intuitively I'm guessing that would be a lot more complex (I'm a pessimist though). Any thoughts?

**Comment by thomasplarsson** [comment]
I tried rebasing to get the build to pass but I think I must have done something wrong since I now have such a massive changeset. I will decline this PR and open a new one I think.

**Comment by thomasplarsson** [comment]
I might have been unclear when writing the issue that this PR refers too. I never intended for the issue to be about adding the possibility to deploy gms or the frontend in an SSL mode, only that clients should be able to try to use https. This of course requires some kind of proxy sitting in front of the service which takes care of the SSL part and forwards the unencrypted call to the actual service, in our case we use EC2 LBs.

Is this a blocker for the PR?

**Comment by shirshanka** [comment]
Thanks for the clarification @thomasplarsson, that helps. 
In that case, maybe just document the new environment variables that you have introduced and some example values for them in the appropriate README(s)?

Maybe enabling ssl is a horizontal concern and needs its own separate doc; we can do that as a follow on item.

**Comment by thomasplarsson** [comment]
Thanks @shirshanka. 
I didn't find any better place to document these than as commented out environment variables in each respective components quickstart docker folders, unless I should add a brand new "configuration" section to the Readme's of the components. Do you think this is enough?

**Review by shirshanka — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
