### PR TITLE
feat(react): add configurable logo aspect ratio

### PR DESCRIPTION
**Pull request by martha**
## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Review by gabe-lyons — COMMENTED** [review]
Great! Thanks for this contribution @martha. Could I ask you to also update `src/app/home/HomePageHeader.tsx` (the other location the logo image is rendered) and make sure it also respects the aspect ratio?

**Comment by martha** [comment]
@gabe-lyons good suggestion! The logo wasn't looking distorted on the home page, which is why I didn't update that file. I noticed that in `src/app/home/HomePageHeader.tsx` it specifies only a `width`, no `height`, for the logo image.

That makes me wonder whether the whole aspect ratio approach I outlined here is overthinking. Should I just modify `SearchHeader.tsx` to specify a height (32px) but no width?

**Comment by gabe-lyons** [comment]
@martha I like your suggestion to fix the height of the search icon and let the width flex- this keeps the theme simpler. Let's go with that 👍

**Comment by martha** [comment]
Sure! Here's an updated screen shot after the new commit.
Screen Shot 2021-05-20 at 2 17 04 PM

**Review by shirshanka — APPROVED** [review]
LGTM. Thanks @martha :)

**Pull request merged**
