### PR TITLE
feat(ingest): add env variable to skip cofirmations for automation en…

### PR DESCRIPTION
**Pull request by aseembansal-gogo**
…v, correct message sent after deletion

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by shirshanka** [comment]
Can we just use a `-f/--force` flag on the command line for skipping confirmations? That would make it similar to most other command line tools.

**Comment by aseembansal-gogo** [comment]
@shirshanka We were using this internally so I accidentally made it consistent with our code. Good point usually that is not people do it. Made it consistent.

**Comment by jjoyce0510** [comment]
Thanks Aseem!

**Review by jjoyce0510 — APPROVED** [review]
LGTM.

**Review by shirshanka — APPROVED** [review]
LGTM!

**Pull request merged**
